services:
  - type: web
    name: tienda-celulares
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: DB_HOST
        value: tu_host
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: tienda_user
      - key: DB_PASSWORD
        value: tu_password
      - key: DB_NAME
        value: tienda_db
